### ISSUE TITLE
Works perfect with Arduino UNO, but not with MEGA

### ISSUE THREAD

**Issue by DavidMR91** [JayLooi/RemoteArduino#1]
Is it compatible with Arduino Mega boards? I've been testing for days and with the Arduino Mega it gives me problems and with UNO it works perfectly. If it is not compatible with Mega, how could it be modified to make it work?

**Comment by JayLooi** [comment]
It is not compatible with Arduino Mega as I remembered the bootloaders in both Mega and Uno using different protocol in receiving flash hex data. 

[Mega bootloader](https://github.com/arduino/ArduinoCore-avr/tree/master/bootloaders/stk500v2)
[Uno bootloader](https://github.com/arduino/ArduinoCore-avr/tree/master/bootloaders/optiboot)

You could look into [ESP8266_Interface/ArduinoOTAFirmwareUpdater](https://github.com/JayLooi/RemoteArduino/tree/master/ESP8266_Interface/ArduinoOTAFirmwareUpdater) and try to modify the protocol in the code accordingly. 

Alternatively, you could try to google for the method to burn Mega-compatible optiboot bootloader into your Arduino Mega. (This method would be easier if there is Mega-compatible optiboot)


I am sorry that I couldn't help much on this matter as I don't have Arduino Mega here to try it out.

**Comment by t3ch9** [comment]
> Is it compatible with Arduino Mega boards? I've been testing for days and with the Arduino Mega it gives me problems and with UNO it works perfectly. If it is not compatible with Mega, how could it be modified to make it work?

Hello, when you compile the sketch, which board is selected in the Arduino IDE to generate the hex file?

**Comment by mluthfialhadi** [comment]
I have burn optiboot botloader from [MCUdude MegaCore Optiboot Bootloader](https://github.com/MCUdude/MegaCore/tree/e233a9cb6f8e0d3c64194fcb986d4fadb552c053/avr/bootloaders/optiboot_flash) for my Arduino Mega 2560 using another arduino nano as isp.
I was able to upload the program using the python app. It is only "blink" program.
![Screenshot 2023-12-19 152935](https://github.com/JayLooi/RemoteArduino/assets/59685778/cb50ca76-20ca-4116-a4ff-a40f38506c63)
But the program is not running, then I checked using avrdudess (arduino nano as isp) to verify the program. Avrdudess even cannot detect the Atmega2560. 
![Screenshot 2023-12-19 153258](https://github.com/JayLooi/RemoteArduino/assets/59685778/c51c37d1-3dfe-4825-9d5f-91d60734d24f)
