### ISSUE TITLE
Can we use this with ESP-01

### ISSUE THREAD

**Issue by mdjavedakhtar** [JayLooi/RemoteArduino#3]
Can we use this with ESP-01 if yes how to connect the reset pin ??

**Comment by JayLooi** [comment]
Yes, the chip on ESP-01 is ESP8266 so surely this code can be used with it. 
There are GPIO0 and GPIO2 pins in ESP-01 circuit so you can use either one to connect to Arduino's reset pin.

**Comment by JayLooi** [comment]
@mdjavedakhtar 
Yes, the chip on ESP-01 is ESP8266 so surely this code can be used with it.
There are GPIO0 and GPIO2 pins in ESP-01 circuit so you can use either one to connect to Arduino's reset pin.
