### ISSUE TITLE
[FAILED] Not response from device!

### ISSUE THREAD

**Issue by Prahar08modi** [JayLooi/RemoteArduino#5]
Hello @JayLooi,

This is a great piece of work as the material for OTA updates on Arduino is rare to find on the internet. However, I am currently facing an issue with the update on Arduino UNO where my host application shows that it is connected to MQTT Broker and the device is also online, but even when I try to flash a hex file, it says "**[FAILED] Not response from the device!**". 

![Screenshot from 2022-06-16 09-38-19](https://user-images.githubusercontent.com/29619549/173989313-0673af25-5897-47cd-a476-8650da56b782.png)

Eventually, I want to update the firmware on Arduino Mega, for which you suggested looking for a Mega-compatible optiboot bootloader. I found Mega compatible bootloaders by [MCUdude](https://github.com/MCUdude/MegaCore) and [my_boards](https://github.com/JAndrassy/my_boards). Can you just confirm if these bootloaders are the correct way to make an OTA update in Arduino Mega?

Thanks in advance :)

**Comment by JayLooi** [comment]
Hi @Prahar08modi, 

Did you connect ESP8266 with Arduino UNO as shown in the diagram in README? What I suspect is that either the ESP8266 IO pin to Arduino UNO reset pin connection issue or the UART connection issue. 

As for the Mega-compatible optiboot, the MCUdude seems a suitable one, but I cannot 100% sure about it as I never test it. 

Thank you.
